### ISSUE TITLE
Getting wrong bitmap from cache if changes the image size

### ISSUE THREAD

**Issue by imsanjaysah** [googlesamples/android-DisplayingBitmaps#2]
I want the images with higher resolution so I am giving the screen's height and width as required resolution. But when I am doing this it gives me wrong bitmap from cache on swiping pages. Below mentioned is the code snippet. Kindly tell me how do I fix it?. Thanks in advance.

final DisplayMetrics displayMetrics = new DisplayMetrics();
        ((AppCompatActivity) mContext).getWindowManager().getDefaultDisplay().getMetrics(displayMetrics);
        final int height = displayMetrics.heightPixels;
        final int width = displayMetrics.widthPixels;
        //final int shortest = (height < width ? height : width) / 2;

```
    ImageCache.ImageCacheParams cacheParams =
            new ImageCache.ImageCacheParams(mContext, IMAGE_CACHE_DIR);
    cacheParams.setMemCacheSizePercent(0.25f); // Set memory cache to 25% of app memory

    // The ImageFetcher takes care of loading images into our ImageView children asynchronously
    mImageFetcher = new ImageFetcher(mContext,width, height );
```

**Comment by adamkoch** [comment]
I believe that should work. This isn't really a great forum for Q&A, I would recommend stackoverflow.com instead. Also, this sample is for educational purposes (for this [training class](https://developer.android.com/training/displaying-bitmaps/index.html)), if you are building a real app then I would recommend using an image loading library such as [Glide](https://github.com/bumptech/glide) or [Picasso](http://square.github.io/picasso/) as these libraries handle a lot more than just demonstrating the basics of image loading on Android.
