### ISSUE TITLE
 Problem decoding into existing bitmap

### ISSUE THREAD

**Issue by xiaos** [googlesamples/android-DisplayingBitmaps#3]
I am facing this error, anyone can help?

Exception java.lang.RuntimeException: An error occured while executing doInBackground()
com.test.imageloader.AsyncTask$3.done (AsyncTask.java)
java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
java.util.concurrent.FutureTask.setException (FutureTask.java:223)
java.util.concurrent.FutureTask.run (FutureTask.java:242)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
arrow_drop_down

Caused by java.lang.IllegalArgumentException: Problem decoding into existing bitmap
android.graphics.BitmapFactory.decodeFileDescriptor (BitmapFactory.java:937)
com.test.imageloader.ImageResizer.setImageSize (ImageResizer.java)
__null__.processBitmap (ImageResizer.java)
__null__.decodeSampledBitmapFromResource (ImageResizer.java)
__null__.decodeSampledBitmapFromDescriptor (ImageResizer.java)
__null__.addInBitmapOptions (ImageResizer.java)
__null__.calculateInSampleSize (ImageResizer.java)
com.test.imageloader.ImageCache.getBitmapFromDiskCache (ImageCache.java)
__null__.clearCache (ImageCache.java)
com.test.imageloader.ImageWorker$BitmapWorkerTask.doInBackground (ImageWorker.java)
__null__.onPostExecute (ImageWorker.java)
__null__.doInBackground (ImageWorker.java)
__null__.access$100 (ImageWorker.java)
com.test.imageloader.ImageWorker$BitmapWorkerTask.doInBackground (ImageWorker.java)
__null__.onPostExecute (ImageWorker.java)
__null__.doInBackground (ImageWorker.java)
__null__.access$100 (ImageWorker.java)
com.test.imageloader.AsyncTask$2.call (AsyncTask.java)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)

**Comment by adamkoch** [comment]
For image loading in a production app, I highly recommend you use one of the well tested image loading libraries such as Glide (https://github.com/bumptech/glide) or Picasso (http://square.github.io/picasso/). This code sample is meant to be illustrative (along with the training class) rather than something you should use in a real world app.
