### ISSUE TITLE
Bitmap can get recycled while still in use

### ISSUE THREAD

**Issue by dco123** [googlesamples/android-DisplayingBitmaps#4]
In the image grid, if you scroll down to bring another image into view it will load that image and add it to the memory cache. If that memory cache then goes over its limit it will release another bitmap from the cache, but there's no guarantee that the released bitmap isn't still in use and visible on screen. The effect of this is when this released bitmap is reused, if it's still on screen then the new image will appear in two grid items.

Unlikely to happen in the sample given the size of the images but i've been expanding on the sample and have hit this issue.

Thanks

**Comment by adamkoch** [comment]
Thanks for pointing this out. I would consider this sample along with the corresponding training class (https://developer.android.com/training/displaying-bitmaps/) to be more for theory at this point. For practical, real-world bitmap loading I would recommend using a well tested library, such as Glide (https://github.com/bumptech/glide) or Picasso (http://square.github.io/picasso/).

We plan to make updates to the sample and documentation to note this soon.
