### ISSUE TITLE
DiskLruCache doesn't flush to journal after committing

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-DisplayingBitmaps#7]
completeEdit should have journalWriter.flush() after writing CLEAN or REMOVE entry, otherwise it often doesn't write it, and forces refetch from server

**Comment by adamkoch** [comment]
Thanks for the report. DiskLruCache in this sample was pulled from AOSP at the time it was created (many years ago). I don't think it's even part of AOSP anymore, but there are more recent versions on github or as part of okhttp that may address this issue. Alternatively, we highly recommend using a dedicated image loading library (such as Glide) which handles disk caching for you.
