### ISSUE TITLE
sometime cause resource leaks

### ISSUE THREAD

**Issue by yglx** [googlesamples/android-DisplayingBitmaps#9]
when I add an 3M picture url and open the some ImageDetailActivity frequently,log shows
com.example.android.displayingbitmaps E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. java.lang.Throwable: Explicit termination method 'close' not called at dalvik.system.CloseGuard.open(CloseGuard.java:223) at java.io.FileOutputStream.<init>(FileOutputStream.java:224) at java.io.FileOutputStream.<init>(FileOutputStream.java:171) at com.example.android.displayingbitmaps.util.DiskLruCache$Editor.newOutputStream(DiskLruCache.java:819) at com.example.android.displayingbitmaps.util.ImageFetcher.processBitmap(ImageFetcher.java:215) at com.example.android.displayingbitmaps.util.ImageFetcher.processBitmap(ImageFetcher.java:257) at com.example.android.displayingbitmaps.util.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:312) at com.example.android.displayingbitmaps.util.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:257) at com.example.android.displayingbitmaps.util.AsyncTask$2.call(AsyncTask.java:313) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764)
how it happened

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
